basePath: /
host: 0.0.0.0:8080
info:
  contact:
    email: by@artisan.io
    name: Artisan
    url: http://www.by_artisan.io/support
  description: app для распределённых систем.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: app by artisan
  version: "0.1"
paths: {}
swagger: "2.0"
