---
- name: Создаём каталог
  ansible.builtin.file:
    path: "{{ prometheus_data_path }}"
    state: directory
    mode: '0755'

- name: Копируем настройки Prometheus
  ansible.builtin.template:
    src: prometheus.yml.j2
    dest: "{{ prometheus_copy_dest }}"

- name: Запускаем контейнер с Prometheus
  community.docker.docker_container:
    name: "{{ prometheus_container_name }}"
    image: "{{ prometheus_image }}"
    restart_policy: always
    ports:
      - "{{ prometheus_outside_port }}:9090"
    volumes:
      - "{{ prometheus_data_path }}:{{ prometheus_config_path }}"
    networks:
      - name: "{{ docker_network }}"

- name: Ожидаем доступ Prometheus
  ansible.builtin.uri:
    url: "http://{{ hostvars[inventory_hostname].ansible_host }}:{{ prometheus_outside_port }}"
    method: GET
    status_code: 200
  register: prometheus_check
  retries: "{{ prometheus_check_retries }}"
  delay: "{{ prometheus_check_delay }}"
  until: prometheus_check.status == 200

- name: Выводим адрес запущенного Prometheus
  ansible.builtin.debug:
    msg: "http://{{ hostvars[inventory_hostname].ansible_host }}:{{ prometheus_outside_port }}"