---
- name: Качаем postgres_exporter
  ansible.builtin.get_url:
    url: "https://github.com/prometheus-community/postgres_exporter/releases/download/v{{ postgres_exporter_version }}/postgres_exporter-{{ postgres_exporter_version }}.linux-amd64.tar.gz"
    dest: "/tmp/postgres_exporter.tar.gz"
    mode: '0755'

- name: Разархивируем postgres_exporter
  ansible.builtin.unarchive:
    src: "/tmp/postgres_exporter.tar.gz"
    dest: "/usr/local/bin"
    remote_src: yes
    extra_opts: "--strip-components=1"
    creates: "/usr/local/bin/postgres_exporter"

- name: Создаём systemd сервис для postgres_exporter
  ansible.builtin.template:
    src: postgres_exporter.service.j2
    dest: /etc/systemd/system/postgres_exporter.service
    owner: root
    group: root
    mode: '0644'

- name: Убеждаемся что postgres_exporter service is enabled and started
  ansible.builtin.systemd:
    name: postgres_exporter
    state: started
    enabled: yes
    daemon_reload: yes
    scope: system